[project]
name = "aau-spritegen"
version = "0.1.1"
description = "CLI for building MapLibre sprite files"
authors = [
    {name = "Kasper Fromm Pedersen", email = "kasperf@cs.aau.dk"},
]
dependencies = [
    "typer==0.26.*",
    "pyvips[binary]==3.1.*",
]
requires-python = ">=3.10,<3.14"
readme = "README.md"
license = {text = "MIT"}

[dependency-groups]
dev = [
    "pyinstaller==6.20.*",
    "distro==1.9.*",
]

[project.scripts]
spritegen = "aau_spritegen.main:app"

[tool.uv]
package = true